import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

import en from "./locales/en.json";
import de from "./locales/de.json";
import sr from "./locales/sr.json";
import fr from "./locales/fr.json";
import es from "./locales/es.json";
import pt from "./locales/pt.json";
import ru from "./locales/ru.json";
import zh from "./locales/zh.json";
import zhHant from "./locales/zh-Hant.json";
import hi from "./locales/hi.json";
import ar from "./locales/ar.json";

// All supported UI languages. Locale files for everything beyond en/de are
// generated by scripts/translate.mjs (LM Studio) and registered in `resources`
// below once they exist. Missing ones fall back to English.
export const SUPPORTED_LANGUAGES = [
  { code: "en", label: "English", native: "English" },
  { code: "de", label: "German", native: "Deutsch" },
  { code: "sr", label: "Serbian", native: "Srpski" },
  { code: "fr", label: "French", native: "Français" },
  { code: "es", label: "Spanish", native: "Español" },
  { code: "pt", label: "Portuguese", native: "Português" },
  { code: "ru", label: "Russian", native: "Русский" },
  { code: "zh", label: "Chinese (Simplified)", native: "简体中文" },
  { code: "zh-Hant", label: "Chinese (Traditional)", native: "繁體中文" },
  { code: "hi", label: "Hindi", native: "हिन्दी" },
  { code: "ar", label: "Arabic", native: "العربية" }
];

// Right-to-left languages — drive the <html dir> attribute.
export const RTL_LANGUAGES = ["ar"];

const resources = {
  en: { translation: en },
  de: { translation: de },
  sr: { translation: sr },
  fr: { translation: fr },
  es: { translation: es },
  pt: { translation: pt },
  ru: { translation: ru },
  zh: { translation: zh },
  "zh-Hant": { translation: zhHant },
  hi: { translation: hi },
  ar: { translation: ar }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: "en",
    supportedLngs: SUPPORTED_LANGUAGES.map((l) => l.code),
    nonExplicitSupportedLngs: true, // map e.g. "de-DE" -> "de"
    detection: {
      order: ["localStorage", "navigator"],
      lookupLocalStorage: "vs-lang",
      caches: ["localStorage"]
    },
    interpolation: { escapeValue: false }, // React already escapes
    returnObjects: true // needed for faq.items array
  });

// Reflect the active language on <html lang>/<html dir> for font, script and
// RTL switching in CSS.
function applyHtmlLang(lng) {
  const base = (lng || "en").split("-")[0];
  document.documentElement.setAttribute("lang", lng);
  document.documentElement.setAttribute(
    "dir",
    RTL_LANGUAGES.includes(lng) || RTL_LANGUAGES.includes(base) ? "rtl" : "ltr"
  );
}
applyHtmlLang(i18n.resolvedLanguage || i18n.language || "en");
i18n.on("languageChanged", applyHtmlLang);

export default i18n;
